/*
 * This source file was generated by the Gradle 'init' task
 */
package jexceptions;
import java.io.File;
import java.io.IOException;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testOpenFileGood() {
        try {
            App classUnderTest = new App();
            String fileName = "somefile.txt";
            File f = new File(fileName);    
            f.createNewFile();
            classUnderTest.openFile1(fileName, false);
            f.delete();
        } catch (IOException e) {
            fail("Should not have thrown an exception");   
        }

    }

     @Test void testOpenFileBad() {
        try {
        App classUnderTest = new App();
        String fileName = "somefile.txt";
        classUnderTest.openFile1(fileName, true);
        assert(false);
        } catch (Exception e) {
            assert(true); 
        }
        
    }
}

